namespace Assets.Scripts
{
    public enum Hobby
    {
        Animals,
        Archery,
        Beauty,
        Books,
        Cars,
        Drink,
        Fashion,
        Fishing,
        Flowers,
        Food,
        Football,
        Games,
        Gay,
        Guitar,
        Jewelry,
        Money,
        Music,
        Photo,
        Pictures,
        Running,
        Sex,
        Singing,
        Skate,
        TV,
        Work
    }
}